Repository Azure/cosmos-explorer, pull requests merged in 2020-10, with the labels that each got.

#239 Switch notebook editors to monaco
  package-lock.json
  package.json
  src/Explorer/Controls/NotebookGallery/Cards/__snapshots__/GalleryCardComponent.test.tsx.snap
  src/Explorer/Controls/NotebookGallery/InfoComponent/__snapshots__/InfoComponent.test.tsx.snap
  src/Explorer/Controls/NotebookViewer/NotebookViewerComponent.tsx
  src/Explorer/Controls/NotebookViewer/__snapshots__/NotebookMetadataComponent.test.tsx.snap
  src/Explorer/Controls/Settings/SettingsSubComponents/__snapshots__/ToolTipLabelComponent.test.tsx.snap
  src/Explorer/Graph/GraphExplorerComponent/D3ForceGraph.ts
  src/Explorer/Notebook/NotebookClientV2.ts
  src/Explorer/Notebook/NotebookComponent/NotebookComponentBootstrapper.tsx
  src/Explorer/Notebook/NotebookComponent/contents/file/text-file.tsx
  src/Explorer/Notebook/NotebookComponent/contents/index.tsx
  src/Explorer/Notebook/NotebookComponent/epics.test.ts
  src/Explorer/Notebook/NotebookComponent/epics.ts
  src/Explorer/Notebook/NotebookComponent/store.ts
  src/Explorer/Notebook/NotebookRenderer/NotebookReadOnlyRenderer.tsx
  src/Explorer/Notebook/NotebookRenderer/NotebookRenderer.tsx
  src/Explorer/Notebook/NotebookRenderer/Toolbar.tsx
  src/Terminal/JupyterLabAppFactory.ts
  src/Terminal/index.ts
  src/Utils/arm/request.test.ts
Labels: enhancement

#246 Add Automerge Action
  .github/workflows/automerge.yml
Labels: automerge

#250 Use Github PAT for automerge
  .github/workflows/automerge.yml
Labels: automerge

#245 Remove unused external files
  externals/jquery.dataTables.min.js
  externals/jquery.datatables.js
  externals/jquery.min.js
  externals/jquery.typeahead.css
  externals/jquery.typeahead.js
  externals/jquery.ui.position.js
  src/Main.ts
Labels: automerge

#149 Test Output Cleanup
  src/Explorer/Controls/NotebookGallery/CodeOfConductComponent.test.tsx
  src/Explorer/DataSamples/ContainerSampleGenerator.test.ts
  src/Explorer/DataSamples/ContainerSampleGenerator.ts
  src/Explorer/Graph/GraphExplorerComponent/ArraysByKeyCache.ts
  src/Explorer/Graph/GraphExplorerComponent/GremlinClient.ts
  src/Explorer/Graph/GraphExplorerComponent/GremlinSimpleClient.ts
  src/Explorer/Graph/GraphExplorerComponent/__mocks__/GremlinClient.ts
Labels: automerge

#257 Fix database offers not loaded when add collection pane is opened
  src/Explorer/Explorer.ts
Labels: automerge

#254 Fix notebook kernel selection and auto-kernel-start
  src/Explorer/Notebook/NotebookClientV2.ts
  src/Explorer/Notebook/NotebookComponent/NotebookComponentBootstrapper.tsx
  src/Explorer/Notebook/NotebookComponent/epics.test.ts
  src/Explorer/Notebook/NotebookComponent/epics.ts
  src/Explorer/Notebook/NotebookComponent/store.test.ts
  src/Explorer/Notebook/NotebookComponent/store.ts
  src/Explorer/Notebook/notebookClientV2.test.ts
Labels: bug fix

#261 Fix Blackforest Origin check
  src/ConfigContext.ts
  src/Utils/MessageValidation.test.ts
Labels: automerge

#259 Move update offers call to RP
  src/Common/DataAccessUtilityBase.ts
  src/Common/DocumentClientUtilityBase.ts
  src/Common/dataAccess/readDatabaseOffer.ts
  src/Common/dataAccess/updateCollection.ts
  src/Common/dataAccess/updateOffer.ts
  src/Contracts/DataModels.ts
  src/Explorer/Controls/Settings/SettingsComponent.test.tsx
  src/Explorer/Controls/Settings/SettingsComponent.tsx
  src/Explorer/Tabs/DatabaseSettingsTab.ts
  src/Explorer/Tabs/SettingsTab.ts
  src/Explorer/Tree/Database.ts
Labels: automerge

#260 Fix horizontal scrollbar in notebook cell input issue
  src/Explorer/Notebook/NotebookRenderer/base.css
Labels: bug fix

#242 Add more Telemetry to Data Explorer
  src/Explorer/Controls/TreeComponent/TreeComponent.tsx
  src/Explorer/Controls/TreeComponent/__snapshots__/TreeComponent.test.tsx.snap
  src/Explorer/Menus/CommandBar/CommandBarComponentAdapter.tsx
  src/Explorer/Menus/CommandBar/CommandBarUtil.test.tsx
  src/Explorer/Menus/CommandBar/CommandBarUtil.tsx
  src/Explorer/Notebook/NotebookComponent/epics.ts
  src/Explorer/Notebook/NotebookComponent/reducers.ts
  src/Explorer/Notebook/NotebookRenderer/Toolbar.tsx
  src/Explorer/Tree/ResourceTreeAdapter.tsx
  src/Shared/Telemetry/TelemetryConstants.ts
Labels: automerge, enhancement

#266 Fix double-scrollbar bug
  less/documentDB.less
Labels: automerge

#255 Update README.md
  README.md
Labels: automerge

#263 Restore AppInsights fetch telemetry
  package-lock.json
  package.json
  src/Shared/appInsights.ts
Labels: automerge

#248 Remove jquery.contextMenu
  externals/jquery.contextMenu.css
  externals/jquery.contextMenu.js
  src/Definitions/jquery.contextmenu.d.ts
  src/Explorer/Tables/DataTable/DataTableContextMenu.ts
  src/Explorer/Tables/DataTable/DataTableOperationManager.ts
  src/Explorer/Tables/DataTable/TableEntityListViewModel.ts
  src/Main.ts
Labels: automerge

#252 All events should trigger and ADO build
  azure-pipelines.cg.yml
Labels: automerge

#256 Remove Explorer.isEmulator
  src/Explorer/Controls/Settings/SettingsComponent.test.tsx
  src/Explorer/Controls/Settings/SettingsSubComponents/ScaleComponent.test.tsx
  src/Explorer/Controls/Settings/SettingsSubComponents/ScaleComponent.tsx
  src/Explorer/Controls/Settings/SettingsSubComponents/SubSettingsComponent.test.tsx
  src/Explorer/Controls/Settings/TestUtils.tsx
  src/Explorer/Controls/Settings/__snapshots__/SettingsComponent.test.tsx.snap
  src/Explorer/Explorer.ts
  src/Explorer/Menus/CommandBar/CommandBarComponentButtonFactory.ts
  src/Explorer/Panes/AddCollectionPane.test.ts
  src/Explorer/Panes/AddCollectionPane.ts
  src/Explorer/Panes/AddDatabasePane.test.ts
  src/Explorer/Panes/AddDatabasePane.ts
  src/Explorer/Panes/CassandraAddCollectionPane.ts
  src/Explorer/Panes/DeleteCollectionConfirmationPane.test.ts
  src/Explorer/Panes/DeleteDatabaseConfirmationPane.test.ts
  src/Explorer/Panes/SettingsPane.test.ts
  src/Explorer/Tabs/DatabaseSettingsTab.ts
  src/Explorer/Tabs/DocumentsTab.test.ts
  src/Explorer/Tabs/QueryTab.test.ts
  src/Explorer/Tabs/SettingsTab.test.ts
  src/Explorer/Tabs/SettingsTab.ts
  src/Explorer/Tabs/TabsManager.test.ts
  src/Platform/Emulator/ExplorerFactory.ts
  src/Platform/Hosted/ExplorerFactory.ts
  src/Platform/Portal/ExplorerFactory.ts
  src/RouteHandlers/TabRouteHandler.test.ts
Labels: automerge

#272 Escape quotes in identifiers in CQL queries
  src/Explorer/Tables/CqlUtilities.test.ts
  src/Explorer/Tables/CqlUtilities.ts
  src/Explorer/Tables/DataTable/TableEntityListViewModel.ts
  src/Explorer/Tables/QueryBuilder/QueryBuilderViewModel.ts
  src/Explorer/Tables/QueryBuilder/QueryViewModel.ts
Labels: automerge

#238 Add summary to each table of the DataTable for narrator context
  src/Explorer/Tables/Constants.ts
  src/Explorer/Tables/DataTable/DataTableBindingManager.ts
Labels: automerge

#268 Remove database offers cache and get offer directly from database
  src/Explorer/Controls/Settings/__snapshots__/SettingsComponent.test.tsx.snap
  src/Explorer/Panes/AddCollectionPane.ts
Labels: automerge

#273 Remove AutoMerge Github Action
  .github/workflows/automerge.yml
Labels: automerge

#265 Add Report Abuse dialog for public gallery notebooks
  src/Explorer/Controls/DialogReactComponent/DialogComponent.tsx
  src/Explorer/Controls/NotebookGallery/GalleryViewerComponent.tsx
  src/Explorer/Controls/NotebookGallery/InfoComponent/InfoComponent.tsx
  src/Explorer/Controls/NotebookGallery/__snapshots__/GalleryViewerComponent.test.tsx.snap
  src/Explorer/Controls/NotebookViewer/NotebookMetadataComponent.test.tsx
  src/Explorer/Controls/NotebookViewer/NotebookMetadataComponent.tsx
  src/Explorer/Controls/NotebookViewer/NotebookViewerComponent.tsx
  src/Explorer/Controls/NotebookViewer/__snapshots__/NotebookMetadataComponent.test.tsx.snap
  src/Explorer/Explorer.ts
  src/Explorer/Notebook/NotebookManager.ts
  src/Juno/JunoClient.test.ts
  src/Juno/JunoClient.ts
  src/Utils/GalleryUtils.ts
Labels: automerge

#278 Use SDK calls to read and update shared throughput for Tables API
  src/Common/dataAccess/readDatabaseOffer.ts
  src/Common/dataAccess/updateOffer.ts
  src/Explorer/Tree/Database.ts
Labels: automerge

#280 Use RP to read databases for all API
  src/Common/dataAccess/readDatabases.ts
Labels: automerge

#279 Remove window.dataExplorerPlatform
  src/Common/CosmosClient.test.ts
  src/Explorer/Controls/Settings/SettingsSubComponents/ScaleComponent.test.tsx
  src/Explorer/Controls/Settings/SettingsSubComponents/ScaleComponent.tsx
  src/Explorer/Controls/Settings/SettingsSubComponents/__snapshots__/ScaleComponent.test.tsx.snap
  src/Explorer/Explorer.ts
  src/Explorer/Menus/CommandBar/CommandBarComponentButtonFactory.ts
  src/Explorer/Panes/AddCollectionPane.ts
  src/Explorer/Panes/AddDatabasePane.ts
  src/Explorer/Tabs/DatabaseSettingsTab.ts
  src/Explorer/Tabs/MongoShellTab.ts
  src/Explorer/Tabs/SettingsTab.ts
  src/Explorer/Tree/Collection.ts
  src/Main.ts
  src/Platform/Emulator/ExplorerFactory.ts
  src/Platform/Emulator/Main.ts
  src/Platform/Hosted/ExplorerFactory.ts
  src/Platform/Hosted/Main.ts
  src/Platform/Portal/ExplorerFactory.ts
  src/Platform/Portal/Main.ts
  src/PlatformType.ts
  src/TokenProviders/TokenProviderFactory.ts
  src/Utils/AuthorizationUtils.test.ts
  src/Utils/AuthorizationUtils.ts
  src/global.d.ts
  tsconfig.strict.json
Labels: automerge

#275 Support async notebook publishing
  src/Explorer/Controls/NotebookGallery/Cards/GalleryCardComponent.test.tsx
  src/Explorer/Controls/NotebookGallery/GalleryViewerComponent.tsx
  src/Explorer/Controls/NotebookGallery/InfoComponent/InfoComponent.tsx
  src/Explorer/Controls/NotebookGallery/__snapshots__/GalleryViewerComponent.test.tsx.snap
  src/Explorer/Controls/NotebookViewer/NotebookMetadataComponent.test.tsx
  src/Explorer/Panes/PublishNotebookPaneAdapter.tsx
  src/Explorer/Panes/PublishNotebookPaneComponent.tsx
  src/Explorer/Panes/__snapshots__/PublishNotebookPaneComponent.test.tsx.snap
  src/Juno/JunoClient.test.ts
  src/Juno/JunoClient.ts
  src/Utils/GalleryUtils.test.ts
  src/Utils/GalleryUtils.ts
Labels: automerge

#281 Move stored procedure operations to RP
  src/Common/dataAccess/createStoredProcedure.ts
  src/Common/dataAccess/deleteStoredProcedure.ts
  src/Common/dataAccess/readOffers.ts
  src/Common/dataAccess/readStoredProcedures.ts
  src/Common/dataAccess/updateStoredProcedure.ts
Labels: automerge

#282 Fix two bugs with tables database offer
  src/Common/dataAccess/readDatabases.ts
  src/Common/dataAccess/updateOffer.ts
Labels: automerge

#283 Move UDF and trigger operations to RP
  src/Common/dataAccess/createStoredProcedure.ts
  src/Common/dataAccess/createTrigger.ts
  src/Common/dataAccess/createUserDefinedFunction.ts
  src/Common/dataAccess/deleteTrigger.ts
  src/Common/dataAccess/deleteUserDefinedFunction.ts
  src/Common/dataAccess/readTriggers.ts
  src/Common/dataAccess/readUserDefinedFunctions.ts
  src/Common/dataAccess/updateStoredProcedure.ts
  src/Common/dataAccess/updateTrigger.ts
  src/Common/dataAccess/updateUserDefinedFunction.ts
  src/Explorer/Tree/UserDefinedFunction.ts
Labels: automerge

#293 Fixed Collections for Mongo can have 20gb
  src/Explorer/Panes/AddCollectionPane.html
Labels: automerge

#294 Fix error handling in DE
  src/Common/CosmosClient.ts
  src/Common/DocumentClientUtilityBase.ts
  src/Common/ErrorHandlingUtils.ts
  src/Common/QueriesClient.ts
  src/Common/dataAccess/createCollection.ts
  src/Common/dataAccess/createDatabase.ts
  src/Common/dataAccess/createStoredProcedure.ts
  src/Common/dataAccess/createTrigger.ts
  src/Common/dataAccess/createUserDefinedFunction.ts
  src/Common/dataAccess/deleteCollection.ts
  src/Common/dataAccess/deleteDatabase.ts
  src/Common/dataAccess/deleteStoredProcedure.ts
  src/Common/dataAccess/deleteTrigger.ts
  src/Common/dataAccess/deleteUserDefinedFunction.ts
  src/Common/dataAccess/readCollection.ts
  src/Common/dataAccess/readCollectionOffer.ts
  src/Common/dataAccess/readCollectionQuotaInfo.ts
  src/Common/dataAccess/readCollections.ts
  src/Common/dataAccess/readDatabaseOffer.ts
  src/Common/dataAccess/readDatabases.ts
  src/Common/dataAccess/readOffers.ts
  src/Common/dataAccess/readStoredProcedures.ts
  src/Common/dataAccess/readTriggers.ts
  src/Common/dataAccess/readUserDefinedFunctions.ts
  src/Common/dataAccess/sendNotificationForError.ts
  src/Common/dataAccess/updateCollection.ts
  src/Common/dataAccess/updateOffer.ts
  src/Common/dataAccess/updateStoredProcedure.ts
  src/Common/dataAccess/updateTrigger.ts
  src/Common/dataAccess/updateUserDefinedFunction.ts
  src/Explorer/Explorer.ts
  src/Explorer/Graph/GraphExplorerComponent/GraphExplorer.tsx
  src/Explorer/Graph/GraphExplorerComponent/GremlinClient.ts
  src/Explorer/Notebook/NotebookComponent/store.ts
  src/Explorer/Panes/BrowseQueriesPane.ts
  src/Explorer/Panes/RenewAdHocAccessPane.ts
  src/Explorer/Panes/SaveQueryPane.ts
  src/Explorer/Panes/SetupNotebooksPane.ts
  src/Explorer/Tabs/DocumentsTab.ts
  src/Explorer/Tree/Collection.ts
  src/Explorer/Tree/Database.ts
  src/Explorer/Tree/StoredProcedure.ts
  src/GitHub/GitHubContentProvider.ts
  src/HostedExplorer.ts
  src/Platform/Hosted/Main.ts
  src/workers/upload/index.ts
Labels: automerge

#295 Use SDK calls for stored procedure, trigger, and UDF operations for Gemlin API
  src/Common/dataAccess/createStoredProcedure.ts
  src/Common/dataAccess/createTrigger.ts
  src/Common/dataAccess/createUserDefinedFunction.ts
  src/Common/dataAccess/deleteStoredProcedure.ts
  src/Common/dataAccess/deleteTrigger.ts
  src/Common/dataAccess/deleteUserDefinedFunction.ts
  src/Common/dataAccess/readStoredProcedures.ts
  src/Common/dataAccess/readTriggers.ts
  src/Common/dataAccess/readUserDefinedFunctions.ts
  src/Common/dataAccess/updateStoredProcedure.ts
  src/Common/dataAccess/updateTrigger.ts
  src/Common/dataAccess/updateUserDefinedFunction.ts
Labels: automerge

#288 Pass subscriptionId when publishing/accessing published notebooks
  src/Juno/JunoClient.test.ts
  src/Juno/JunoClient.ts
Labels: automerge

#296 Remove extra error logging in SettingsComponent
  src/Explorer/Controls/Settings/SettingsComponent.tsx
Labels: automerge

#289 Fix notebook code complete selected dropdown item background color
  src/Explorer/Notebook/NotebookRenderer/NotebookRenderer.less
Labels: automerge, bug fix

#299 Allow users to switch between manual and autoscale for fixed collections
  src/Explorer/Controls/Settings/SettingsSubComponents/ScaleComponent.tsx
  src/Explorer/Controls/Settings/SettingsSubComponents/ThroughputInputComponents/ThroughputInputAutoPilotV3Component.tsx
  src/Explorer/Controls/Settings/SettingsUtils.test.tsx
  src/Explorer/Controls/Settings/SettingsUtils.tsx
  src/Explorer/Controls/ThroughputInput/ThroughputInputComponentAutoscaleV3.html
  src/Explorer/Tabs/SettingsTab.ts
Labels: automerge

#305 Update @nteract/monaco-editor package to get c# syntax coloring bug fix
  package-lock.json
  package.json
Labels: automerge

#307 refactor error handling part 1
  src/Common/CosmosClient.ts
  src/Common/ErrorHandlingUtils.ts
  src/Common/ErrorParserUtility.ts
  src/Common/Logger.ts
  src/Common/QueriesClient.ts
  src/Common/dataAccess/createTrigger.ts
  src/Common/dataAccess/readOffers.ts
  src/Common/dataAccess/sendNotificationForError.ts
  src/Common/dataAccess/updateOfferThroughputBeyondLimit.ts
  src/Explorer/Controls/Settings/SettingsComponent.tsx
  src/Explorer/Explorer.ts
  src/Explorer/Graph/GraphExplorerComponent/GraphExplorer.tsx
  src/Explorer/Graph/GraphExplorerComponent/GremlinClient.ts
  src/Explorer/Panes/AddCollectionPane.ts
  src/Explorer/Panes/BrowseQueriesPane.ts
  src/Explorer/Panes/RenewAdHocAccessPane.ts
  src/Explorer/Panes/SaveQueryPane.ts
  src/Explorer/Panes/SetupNotebooksPane.ts
  src/Explorer/Tabs/DocumentsTab.ts
  src/Explorer/Tabs/SettingsTab.ts
  src/Explorer/Tree/Collection.ts
  src/Explorer/Tree/Database.ts
  src/Explorer/Tree/StoredProcedure.ts
  src/GitHub/GitHubContentProvider.ts
  src/HostedExplorer.ts
  src/Platform/Hosted/Main.ts
  src/workers/upload/index.ts
  tsconfig.strict.json
Labels: automerge
